
function playback(opts) {
  var records = [];

  function record(key, data) {
    records.push({key: key, data: data});
  }

  function playback() {
    var lines = [
        '// Auto-generated by record-playback',
        '',
        'Map<String, String> playBackData = {'
    ];

    records.forEach(function(r) {
      lines.push('  \'' + r.key + '\': \'' + r.data + '\',')
    });

    lines.push('};');

    return lines.join('\n');
  }

  return {
    record: record,
    playback: playback
  }
}

module.exports = {
  playback: playback
};
